---
name: Contributor Activity
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      'KKBranch'
# on:
  # schedule:
    # - cron: '13 6 * * *'
    # every night at 6:13am Zulu (about 2am EST)

jobs:
  FindContributorActivity:
    runs-on: ubuntu-latest
    steps:
      - name: Begin Setup
        uses: actions/checkout@v1
      - name: Get contributors in json
        # yamllint disable rule:line-length
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/stats/contributors \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' > contribute.json
      - name: Run Contributor Stats
        run: python .github/ciPython/contributor_stats.py contribute.json
      - name: Commit daily and total commits
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub  Action"
          git add ./html/cidata/weekly_commits.js
          git commit -m "Daily and Total Contributor Commits" -a
      # yamllint enable rule:line-length
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'KKBranch'
