name: Report Issues
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches-ignore:
      - 'KKBranch'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Begin Setup
        uses: actions/checkout@master
        with:
          # otherwise, the token used is the GITHUB_TOKEN
          persist-credentials: false
          # otherwise, you will failed to push refs to dest repo
          fetch-depth: 0
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
      - name: Get Issues
      # yamllint disable rule:line-length
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' > issues.json
      # yamllint enable rule:line-length
      - name: Upload Issues json to artifact
        uses: actions/upload-artifact@v1
        with:
          name: Issues-Stats
          path: issues.json
