name: Java Hello World
on:
  push:
    branches-ignore: 
      - Math-Test-Passing-By-Failing*'
  pull_request:
    branches:
      - "*"
jobs:

  build:
    name: "JavaHelloWorld"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/HelloWorldTest
