name: JavaTest-Maven

on: 
  push:
    branches:
      - 'JavaTest'
  pull_request:
    branches: 
      - 'master'
      - '!update-documentation' # you can only use branches or branches-ignore
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: ./.github/actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
