name: Java Hello World

on:
  push:
    branches:
      - 'JavaTest'
#BSD for now hiding this from running outside of this branch
#  pull_request:
#    branches:
#      - 'master'
#      - '!update-documentation'
jobs:

  build:
    name: "JavaHelloWorld"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/HelloWorldTest
