name: Java Hello World

on: 
  push:
    branches:
      - 'JavaTest'
  pull_request:
    branches: 
      - 'master'
jobs:

  build:
    name: "JavaHelloWorld"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/HelloWorldTest
