name: Math Tests verifying parameters
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Successful math test
      uses: ./.github/actions/mathTest
      with:
        OPERAND1: 3
        OPERAND2: 5
        ANSWER: 2
  testing-failure:
    runs-on: ubuntu-latest
    steps:
    - name: Mismatch answer math test
      if: $!{{ always() }}
      uses: ./.github/actions/mathTest
      with:
        OPERAND1: -3
        OPERAND2: 2
        ANSWER: 1 '
    - name: Missing operand math test
      if: ${{ always() }}
      uses: ./.github/actions/mathTest
      with:
        OPERAND1: -3
        ANSWER: 5
  outcome: ${{success}}
    
      
