---
name: Repository report
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      'KKBranch'
jobs:
  report:
    runs-on: ubuntu-latest
    name: Begin report
    steps:
      #$- name: Process commits
        #run: |
        #  curl --request GET \
        #  --url https://api.github.com/repos/${{ github.repository }}/commits \
        #  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        #  --header 'content-type: application/json' \
      - name: Retrive failed actions
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/commits/KKBranch/status?state=failure \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
      - name: Retrive passed actions
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/commits/KKBranch/status?state=success \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
      #- name: List issue comments for this repository
      #  run: |
      #    curl --request GET \
      #    --url https://api.github.com/repos/${{ github.repository }}/issues/comments \
      #    --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #    --header 'content-type: application/json' \
      - name: Store in artifact
        uses: actions/upload-artifact@v1
        with:
          name: Report Log
          path: log.log
