---
name: Repository report
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      'KKBranch'
jobs:
  report:
    runs-on: ubuntu-latest
    name: Begin report
    steps:
      - name: Process commits
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/commits \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
      - name: List issue comments for this repository
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/issues/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
      - name: Get feeds
        run: |
          curl --request GET \
          --url https://api.github.com/repos/feeds \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
