---
name: Repository report
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      'KKBranch'
jobs:
  report:
    runs-on: ubuntu-latest
    name: Begin report
    steps:
      - name: Process report
        run:
          curl https://api.github.com/repos/${{ github.repository }}/commits \ 
