---
name: Repository report
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      'KKBranch'
    # every Sunday night at a min past midnight (weekly report)
    # - cron: '1 0 * * 0'
jobs:
  get_data:
    runs-on: ubuntu-latest
    name: Extract data and put into json artifact
    steps:
      - name: Begin Setup
        uses: actions/checkout@master
        with:
          # otherwise, the token used is the GITHUB_TOKEN
          persist-credentials: false
          # otherwise, you will failed to push refs to dest repo
          fetch-depth: 0
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
      - name: Get weekly commit count
        # yamllint disable rule:line-length
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/stats/participation \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' > commit_count.json \
      # yamllint enable rule:line-length
      - name: Commit Count Artifact
        uses: actions/upload-artifact@v1
        with:
          name: weekly-count
          path: commit_count.json
