---
name: Repository report
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      'KKBranch'
jobs:
  report:
    runs-on: ubuntu-latest
    name: Begin report
    steps:
      - name: Process commits
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/commits \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json'
      - name: List of pull requests
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/pulls?state=all \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json'
      - name: Get contributor stats
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/stats/contributors \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json'
      - name: Get stats
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/stats \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json'

  get_data:
    runs-on: ubuntu-latest
    name: Extract data and put into json artifact
    steps:
      - name: Setup code
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
      - name: Get weekly commit count
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/stats/participation \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' > commit_count.json \
      - name: Run ProjectHealth
        run: python .github/workflows/ProjectHealth.py commit_count.json > health.txt
      - uses: actions/checkout@v1
        #./project/frontend/ will exist with checkout action
      - name: Upload artifact that contains project health
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Repos-Stats
          path: ./project/frontend/health.txt
