---
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'justchecking'

jobs:
  secondBox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: box 2
        uses: ./.github/actions/box3
  firstBox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: box 1
        uses: ./.github/actions/box1
