---
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'justchecking'

jobs:
  secondBox:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }} > IP2.txt
      - name: Save IP
        uses: actions/upload-artifact@v2
          with:
            name: IPTwo
            path: IP2.txt
      - name: Get IP
        uses: actions/download-artifact@v2
          with:
            name: IPOne
      - uses: actions/checkout@v1
      - name: box 2
        uses: ./.github/actions/box2
  firstBox:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }} > IP1.txt
      - name: Save IP
        uses: actions/upload-artifact@v2
          with:
            name: IPOne
            path: IP1.txt
      - name: Get IP
        uses: actions/download-artifact@v2
          with:
            name: IPTwo
      - uses: actions/checkout@v1
      - name: box 1
        uses: ./.github/actions/box1
