---
# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'justchecking'

jobs:
  secondBox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }} > IP2.txt
      - name: Save IP
        uses: actions/upload-artifact@v2
        with:
          name: IPTwo
          path: IP2.txt
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '4s'
      - name: Get IP
        uses: actions/download-artifact@v2
        with:
          name: IPOne
      - name: Save File listing
        run: ls -l > out2.txt
      - name: Keep file listing artifact
        uses: actions/upload-artifact@v1
        with:
          name: file2_list
          path: out2.txt
      - name: box 2
        uses: ./.github/actions/box2
  firstBox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }} > IP1.txt
      - name: Save IP
        uses: actions/upload-artifact@v2
        with:
          name: IPOne
          path: IP1.txt
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '4s'
      - name: Get IP
        uses: actions/download-artifact@v2
        with:
          name: IPTwo
      - name: Save File listing
        run: ls -l > out1.txt
      - name: Keep file listing artifact
        uses: actions/upload-artifact@v1
        with:
          name: file1_list
          path: out1.txt
      - name: box 1
        uses: ./.github/actions/box1
