---
name: Audit YML
# Rules for yaml Lint
# https://yamllint.readthedocs.io/en/stable/rules.html

# fix truthy warning per
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-586706596
# yamllint disable-line rule:truthy
#on:
#  push:
#    paths:
#      - ".github/workflows/**.yml"
#      - ".github/workflows/forceYMLAudit.txt"

on:
  schedule:
    # 01:05
    # on Feb 1st if it's a Sunday
    - cron: '5 5 1 2 0'

jobs:
  lintAllYml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
